# Generated by Django 5.1.6 on 2025-03-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomeworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.homeworkmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel')),
            ],
        ),
    ]
