# Generated by Django 5.1.6 on 2025-03-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studenthomeworkmodel'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentHomeworkModel',
            new_name='SubmissionModel',
        ),
    ]
