# Generated by Django 5.1.6 on 2025-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_studenthomeworkmodel_submissionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
