# Generated by Django 5.1.6 on 2025-03-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkmodel',
            name='group',
        ),
        migrations.RemoveField(
            model_name='homeworkmodel',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='managed_by',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='managed_by',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='user',
        ),
    ]
