# Generated by Django 5.1.6 on 2025-03-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_homeworkmodel_group_and_more'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.studentmodel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='teachers.teachermodel'),
        ),
        migrations.DeleteModel(
            name='HomeworkModel',
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
    ]
