# Generated by Django 5.1.6 on 2025-03-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_groupmodel_students_alter_groupmodel_teachers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='admin',
        ),
    ]
