# Generated by Django 5.1.6 on 2025-03-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_remove_groupmodel_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.adminmodel'),
            preserve_default=False,
        ),
    ]
